name: LobbyPlugin
version: '${project.version}'
main: io.github.cardsandhuskers.lobbyplugin.LobbyPlugin
api-version: 1.19
depend: [PlayerPoints, PlaceholderAPI]
softdepend: [Multiverse-Core]
commands:
  setLobby:
    description: sets lobby location
    usage: /<command>
  startEvent:
    description: starts timers
    usage: /<command>
  startRound:
    description: starts the next round
    usage: /<command>
  setGameNumber:
    description: sets the game number that you are currently on
    usage: /<command> [gameNumber]
  removeGame:
    description: remove a game from the voting list
    usage: /<command> [GAME]
  pauseEvent:
    description: pauses the voting or pregame timer (whichever is active)
    usage: /<command>